language: julia

os:
  - linux
  - osx
  - windows

julia:
  - nightly
  - 1.5

matrix:
  allow_failures:
  - julia: nightly

script:
- julia --check-bounds=yes --color=yes --inline=no -e "using Pkg; Pkg.test(coverage=true)"
